DemoHisaab2/Models/Transaction.cs
namespace DemoHisaab2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Transaction")]
    public partial class Transaction
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int TransactionId { get; set; }

        [Required]
        [StringLength(50)]
        public string CreditAccount { get; set; }

        [StringLength(50)]
        public string DebitAccount { get; set; }

        public int Amount { get; set; }

        [Column(TypeName = "date")]
        public DateTime Date { get; set; }

        [StringLength(200)]
        public string Description { get; set; }

        public int UserId { get; set; }

        public virtual User_Details User_Details { get; set; }
    }
}

DemoHisaab2/Controllers/UserHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DemoHisaab2.Models;
using System.Globalization;

namespace DemoHisaab2.Controllers
{
    public class UserHomeController : Controller
    {
        // GET: UserHome
        Hisaab db = new Hisaab();

        public ActionResult Index()
        {
            
            if(Session["UserId"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            return RedirectToAction("DisplayTransaction");
        }
        [AllowAnonymous]
        public ActionResult AccountDetails()
        {
            var result = checkSession();
            if (result != null)
                return result;
            string[] items = { "Bank", "Simple", "Bill" };
            ViewData["AccountType"] = new SelectList(items.AsEnumerable<string>());
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public ActionResult AccountDetails(string InitAmountType,User_Accounts usracc)
        {
            var result = checkSession();
            if (result != null)
                return result;
            int id = Convert.ToInt32(Session["UserId"]);
            if(InitAmountType.Equals("Debit"))
            {
                usracc.TotalAmount = 0 - usracc.TotalAmount;
            }

            using(Hisaab dbx=new Hisaab())
            {
                usracc.UserId = id;
                usracc.User_Details = dbx.User_Details.Find(id);
                dbx.User_Accounts.Add(usracc);
                Transaction trax = new Transaction();
                trax.CreditAccount = usracc.AccountName;
                trax.Amount = usracc.TotalAmount;
                trax.DebitAccount = "";
                trax.Description = "Intialization";
                trax.Date = DateTime.Now;
                trax.UserId = id;
                trax.User_Details= dbx.User_Details.Find(id);
                dbx.Transactions.Add(trax);
                dbx.SaveChanges();
            }
            return RedirectToAction("AccountDetails");
        }

        public ActionResult Transaction()
        {
            var result = checkSession();
            if (result != null)
                return result;
            int id = Convert.ToInt32(Session["UserId"]);
            var usr = db.User_Accounts.Where(p => p.UserId == id);
            var accounts = usr.Select(acc => acc.AccountName);
            ViewData["CreditAccount"] = new SelectList(accounts.AsEnumerable<string>());
            ViewData["DebitAccount"] = new SelectList(accounts.AsEnumerable<string>());
            return View();
        }
        public ActionResult Transaction1()
        {
            var result = checkSession();
            if (result != null)
                return result;
            return View();
        }
        [HttpPost]
        public ActionResult Transaction1(string PreDefinedAcc)
        {
            var result = checkSession();
            if (result != null)
                return result;

            if (PreDefinedAcc.Equals("Yes"))
                return RedirectToAction("Transaction");
            else
                return (RedirectToAction("Transaction2"));
        }
        public ActionResult Transaction2()
        {
            var result = checkSession();
            if (result != null)
                return result;

            int id = Convert.ToInt32(Session["UserId"]);
            var usr = db.User_Accounts.Where(p => p.UserId == id);
            var accounts = usr.Select(acc => acc.AccountName);
            ViewData["CreditAccount"] = new SelectList(accounts.AsEnumerable<string>());
            return View();
        }
        [HttpPost]
        public ActionResult Transaction2(Transaction ts)
        {
            var result = checkSession();
            if (result != null)
                return result;

            int id = Convert.ToInt32(Session["UserId"]);
            User_Accounts usracc = db.User_Accounts.Where(x => x.AccountName.Equals(ts.CreditAccount)).FirstOrDefault();
            usracc.TotalAmount += ts.Amount;
            ts.UserId = id;
            ts.User_Details = db.User_Details.Find(id);

            db.Transactions.Add(ts);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Transaction(Transaction ts)
        {
            var result = checkSession();
            if (result != null)
                return result;

            int id = Convert.ToInt32(Session["UserId"]);
            User_Accounts usracc = db.User_Accounts.Where(x => x.AccountName.Equals(ts.CreditAccount)).FirstOrDefault();
            usracc.TotalAmount += ts.Amount;
            usracc = db.User_Accounts.Where(x => x.AccountName.Equals(ts.DebitAccount)).FirstOrDefault();
            usracc.TotalAmount -= ts.Amount;
            ts.UserId = id;
            ts.User_Details = db.User_Details.Find(id);
            db.Transactions.Add(ts);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult DisplayTransaction()
        {
            var result=checkSession();
            if (result != null)
                return result;

            int id = Convert.ToInt32(Session["UserId"]);
            var ts = db.Transactions.Where(t => t.UserId == id).OrderByDescending(x=>x.Date);
            return View(ts);
        }
        public ActionResult ShowAccountTransaction(string AccountName)
        {
            var result = checkSession();
            if (result != null)
                return result;

            int id = Convert.ToInt32(Session["UserId"]);
            var trs = db.Transactions.Where(ac => ac.UserId == id && (ac.CreditAccount == AccountName || ac.DebitAccount == AccountName)).OrderByDescending(x=>x.Date);
            ViewData["accname"] = AccountName;
            return View(trs);
        }
        public ActionResult DispAccounts()
        {
            var result = checkSession();
            if (result != null)
                return result;

            int id = Convert.ToInt32(Session["UserId"]);
            var acc = db.User_Accounts.Where(ac => ac.UserId == id);
            return View(acc);
        }
        public ActionResult DeleteTransaction(int id,string AccountName)
        {
            var result = checkSession();
            if (result != null)
                return result;
            var trs = db.Transactions.Where(ts => ts.TransactionId == id).FirstOrDefault();
            db.Transactions.Remove(trs);
            db.SaveChanges();
            var usracc = db.User_Accounts.Where(ua => ua.AccountName == trs.CreditAccount).FirstOrDefault();
            usracc.TotalAmount -= trs.Amount;
            User_Accounts usac = db.User_Accounts.Where(u => u.AccountName == trs.DebitAccount).FirstOrDefault();
            if (usac != null)
            {
                usac.TotalAmount += trs.Amount;
            }
            db.SaveChanges();
            return RedirectToAction("ShowAccountTransaction",new { AccountName = AccountName});
        }
        public ActionResult DeleteTransaction1(int id)
        {
            var result = checkSession();
            if (result != null)
                return result;

            var trs = db.Transactions.Where(ts => ts.TransactionId == id).FirstOrDefault();
            db.Transactions.Remove(trs);
            db.SaveChanges();
            var usracc = db.User_Accounts.Where(ua => ua.AccountName == trs.CreditAccount).FirstOrDefault();
            usracc.TotalAmount -= trs.Amount;
            User_Accounts usac = db.User_Accounts.Where(u => u.AccountName == trs.DebitAccount).FirstOrDefault();
            if (usac != null)
            {
                usac.TotalAmount += trs.Amount;
            }
            db.SaveChanges();
            return RedirectToAction("DisplayTransaction");
        }

        public ActionResult EditTransaction(int id)
        {
            var result = checkSession();
            if (result != null)
                return result;

            var trs = db.Transactions.Where(ts => ts.TransactionId == id).FirstOrDefault();
            ViewBag.usrId = trs.UserId;
            return View(trs);
        }
        [HttpPost]
        public ActionResult EditTransaction(Transaction ts)
        {
            var result = checkSession();
            if (result != null)
                return result;

            Transaction trs = db.Transactions.Where(t => t.TransactionId == ts.TransactionId).FirstOrDefault();
            if(trs.Date!=ts.Date)
            {
                trs.Date = ts.Date;
            }
            if(!trs.Description.Equals(ts))
            {
                trs.Description = ts.Description;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private ActionResult checkSession()
        {
            int id = Convert.ToInt32(Session["UserId"]);
            string name = Convert.ToString(Session["UserName"]);
            if(id==0 || name==null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return null;
            }
        }

        public ActionResult Filter(string StartDate, string EndDate)
        {
            DateTime StDate = Convert.ToDateTime(DateTime.ParseExact(StartDate, "MM/dd/yyyy", CultureInfo.InvariantCulture));
            DateTime EdDate = Convert.ToDateTime(DateTime.ParseExact(EndDate, "MM/dd/yyyy", CultureInfo.InvariantCulture));
            int id = Convert.ToInt32(Session["UserId"]);
            IEnumerable<Transaction> ts = db.Transactions.Where(t => t.UserId == id && (t.Date <= EdDate && t.Date >= StDate)).OrderByDescending(x=>x.Date).ToList();
            return View("DisplayTransaction",ts);
        }


    }
}

DemoHisaab2/Views/UserHome/AccountDetails.cshtml
@model  DemoHisaab2.Models.User_Accounts

@{
    ViewBag.Title = "AccountDetails";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Add New Account</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.AccountName, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.EditorFor(model => model.AccountName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AccountName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TotalAmount, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.EditorFor(model => model.TotalAmount, new { htmlAttributes = new { @class = "form-control",placeholder=0 } })
            @Html.ValidationMessageFor(model => model.TotalAmount, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("InitAmountType","Type Of Initialization Amount :- ", htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.RadioButton("InitAmountType", "Credit", true) @Html.Label("Credit (You have to take)")
            @Html.RadioButton("InitAmountType", "Debit", false) @Html.Label("Debit (You have to give)")
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AccountType, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.DropDownList("AccountType", null, " ", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AccountType, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-4 col-md-8">
            <input type="submit" value="Add" class="btn btn-default" />
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemoHisaab2/Views/UserHome/DispAccounts.cshtml
@model IEnumerable<DemoHisaab2.Models.User_Accounts>

@{
    ViewBag.Title = "DispAccounts";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<div class="container">
    <h2>Accounts Details</h2>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-sm-4">

                <hr />
                <dl class="dl-horizontal">

                    <dt>
                        @Html.DisplayNameFor(model => model.AccountName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(modelItem => item.AccountName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.TotalAmount)
                    </dt>

                    <dd>
                        @Html.DisplayFor(modelItem => item.TotalAmount)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.AccountType)
                    </dt>

                    <dd>
                        @Html.DisplayFor(modelItem => item.AccountType)
                    </dd>
                    <dt>
                        @Html.ActionLink("Show Transactions", "ShowAccountTransaction", new { id = item.UserId, AccountName = item.AccountName })
                    </dt>
                </dl>
            </div>
        }
    </div>
</div>

DemoHisaab2/Views/UserHome/DisplayTransaction.cshtml
@model IEnumerable<DemoHisaab2.Models.Transaction>

@{
    ViewBag.Title = "DisplayTransaction";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Transactions Details </h2>
<hr />
@using (Html.BeginForm("Filter", "UserHome"))
{
    <div class="col-md-4">
        @Html.Label("Start Date :-", htmlAttributes: new { @class = "control-label " })
        @Html.TextBox("StartDate", null, htmlAttributes: new { @class = "form-control  ", placeholder = "mm/dd/yyyy" })
    </div>
    <div class="col-md-4">
        @Html.Label("End Date :- ", htmlAttributes: new { @class = "control-label " })
        @Html.TextBox("EndDate", null, htmlAttributes: new { @class = "form-control  ", placeholder = "mm/dd/yyyy" })
    </div>
    <div class="col-md-4">
        <input type="submit" value="Filter" class="btn btn-default" />
    </div>
}

<br />
<br />
<br />
<br />



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CreditAccount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DebitAccount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CreditAccount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DebitAccount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditTransaction", new { id = item.TransactionId }) |
                @Html.ActionLink("Delete", "DeleteTransaction1", new { id = item.TransactionId })
            </td>
        </tr>
    }

</table>

DemoHisaab2/Views/UserHome/EditTransaction.cshtml
@model DemoHisaab2.Models.Transaction

@{
    ViewBag.Title = "EditTransaction";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Edit Transaction</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TransactionId)

        <div class="form-group">
            @Html.LabelFor(model => model.CreditAccount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreditAccount, new { htmlAttributes = new { @class = "form-control" ,disabled="disabled"} })
                @Html.ValidationMessageFor(model => model.CreditAccount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DebitAccount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DebitAccount, new { htmlAttributes = new { @class = "form-control",disabled="disabled" } })
                @Html.ValidationMessageFor(model => model.DebitAccount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control",disabled="disabled" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DemoHisaab2/Views/UserHome/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Index</h2>

DemoHisaab2/Views/UserHome/ShowAccountTransaction.cshtml
@model IEnumerable<DemoHisaab2.Models.Transaction>

@{
    ViewBag.Title = "ShowAccountTransaction";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>AccountTransaction</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CreditAccount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DebitAccount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CreditAccount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DebitAccount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditTransaction", new { id = item.TransactionId, AccountName = ViewData["accname"] }) |
                @Html.ActionLink("Delete", "DeleteTransaction", new { id = item.TransactionId, AccountName = ViewData["accname"] })
             </td>
        </tr>
    }

</table>

DemoHisaab2/Views/UserHome/Transaction.cshtml
@model DemoHisaab2.Models.Transaction

@{
    ViewBag.Title = "Transation";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Make Transation</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CreditAccount, "CreditAccount", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CreditAccount", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CreditAccount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DebitAccount, "DebitAccount", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DebitAccount", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DebitAccount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", placeholder = "mm/dd/yyyy" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Transaction" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemoHisaab2/Views/UserHome/Transaction1.cshtml
@{
    ViewBag.Title = "Transation";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Make Transation</h2>


@using (Html.BeginForm())
{

<div class="form-horizontal">
    <hr />
    <div class="form-group">
        <h3>@Html.Label("Select Debit Account Option ", htmlAttributes: new { @class = "control-label col-md-4" })</h3>
    </div>

    <div class="form-group">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            @Html.RadioButton("PreDefinedAcc", "Yes", true) @Html.Label("Use Predefined Account")
            <br />
            @Html.RadioButton("PreDefinedAcc", "No", false) @Html.Label("Don't Use Predefined Account")
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-1 col-md-10">
            <input type="submit" value="Make Transaction" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemoHisaab2/Views/UserHome/Transaction2.cshtml
@model DemoHisaab2.Models.Transaction

@{
    ViewBag.Title = "Transation";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Make Transation</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CreditAccount, "CreditAccount", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CreditAccount", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CreditAccount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DebitAccount, "DebitAccount", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model=>model.DebitAccount,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DebitAccount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", placeholder = "mm/dd/yyyy" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Transaction" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}